### ISSUE TITLE
Support performBatchUpdate

### ISSUE THREAD

**Issue by h0shy** [Blackjacx/Source#12]
Hey there, so far you always call `reloadData` on the table view when the datasource gets updated. It would be more efficient/elegant/pretty to do the diffing first and then insert/delete the items that changed. Pre iOS 13 that is, after that it's just a one liner, but either way `reloadData` ain't ideal. ^^

**Comment by Blackjacx** [comment]
Coed in favor of https://github.com/Blackjacx/Source/issues/19
